### ISSUE TITLE
Problem deleting Functions

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#101]
When there are more than one function in the functions tab. Deleting any of the functions (except the first one) the tab panles becommes grey, until the tab is clicked or scrolled

Having more than one function:
![captura de pantalla de 2015-10-06 13-04-14](https://cloud.githubusercontent.com/assets/2364120/10306941/dd9a18e2-6c2a-11e5-9ee8-fe07cbfbef51.png)

After deleting newCommand6
![captura de pantalla de 2015-10-06 13-04-28](https://cloud.githubusercontent.com/assets/2364120/10306952/e952173e-6c2a-11e5-8d1f-473f4c88487f.png)

@SergioSoto @mfallas

**Comment by SergioSoto** [comment]
Fixed in commit ccd93b3c71
@acepero13 please corroborate that fixes on FunctionsEditor work properly when you have a chance.
