### ISSUE TITLE
Unhandled exception when playin a project that uses invalid functions 

### ISSUE THREAD

**Issue by SergioSoto** [SceneMaker/VisualSceneMaker#102]
How to reproduce:

1. Create new function (eg println(double))
3. Drag this function into a node in the workspace
4. Add any double number as a parameter (eg 1.1)
5. Modify the class path to an invalid one 
6. Run
7. Exception thrown in netbeans output window.

This exception should be handled by the SceneMaker's Error Console

**Comment by mfallas** [comment]
Fixed f4c9e5680efa4f09bcb6aa8ef6b6d7be741da4e0
