### ISSUE TITLE
Commands are displayed /  stored inconsistently

### ISSUE THREAD

**Issue by SceneMaker** [SceneMaker/VisualSceneMaker#104]
Sometimes the display of commands (attached to a node) does not match the display of the in the element editor. We have even discovered a case, wenn removing a command from a node and coming later back to that node the command appears again in the element editor command list - but sometimes not. This is a very (in a bad sense) situation. And sometimes, when changing the name of a command at a node, it gets changed at the node but not in the element editor. Could you try and test this behavior?

Edit by @SergioSoto : This can be reproduced by adding a command definition to a node, the command badge will be displayed correctly. Then erase this command definition and add a new one, the command definition will be shown in the element editor, but no command badge will appear.

**Comment by SergioSoto** [comment]
To add to this issue:
- CommandBadge on Node doesn't show edit value properly, this means that sometimes when double clicking command badge edit command definitions, the command appears hidden in the edit value box (user has to either scroll down or up for the command to appear).
- When modifying a value directly on the command badge, and the command is bigger than the pre-defined box, the user cannot see the rest of the entered text until the workspace is refreshed.

**Comment by SergioSoto** [comment]
Fixed in commit 724624e
@acepero13 and @TengfeiWang  please test this extensively when you have a chance to make sure it is fixed.
