### ISSUE TITLE
Double clicking in node badge doesn't always work

### ISSUE THREAD

**Issue by SergioSoto** [SceneMaker/VisualSceneMaker#105]
Double clicking in node badge to edit command definitions doesn't always work

**Comment by SergioSoto** [comment]
This is fixed in commit dfc9484b

**Comment by SergioSoto** [comment]
Still, when coming back from a SuperNode, double click to edit command badge doesn't work.

**Comment by mfallas** [comment]
After a while struggling to find this error I notice that this happened not only going back but also if you have two nodes with CmdBadges in the same position on two different levels, then the second also doesn't work.

**Comment by mfallas** [comment]
Fixed 8003ee850c908dfb86736be3c8d9bf6c99e9bce5 under tests
