### ISSUE TITLE
Command Badge disappears if node is dragged outside the boundaries of the workspace.

### ISSUE THREAD

**Issue by SergioSoto** [SceneMaker/VisualSceneMaker#106]
Command Badge disappears if node is dragged outside the boundaries of the workspace. It appears again when the workspace is refreshed.

**Comment by SergioSoto** [comment]
This to be the culprit of most Command Badge inconsistencies in big projects where the node charts exceed the size of the workspace. The bug seems to be have always been present.

**Comment by mfallas** [comment]
Fixed 10e8f000d617fe38fe33f0f0e2c3b5b36b6cbce0, under tests
