### ISSUE TITLE
Inconsistent right click

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#108]
Usually when  right click on the workspace the "Add variable" option appears. 
After cut/copy a node then, after the right click the option "Paste" is shown. But after pasting it remains the pasting option available and is no longer possible to get the old "Add variable" option anymore

**Comment by SergioSoto** [comment]
The copied/cutted node stays on the clipboard after pasting. Therefore the user is always shown the option to paste over and over again its contents. We should discuss whether this is intended or not.
@SceneMaker

**Comment by mfallas** [comment]
Fixed 29b9480744c6710272190056692b1e7e5311a744
