### ISSUE TITLE
Problem deleting Functions (Function list)

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#109]
After deleting a function using the minus button in the Functions Tab, the Function list in the upper left side is not updated.
Ex: 
Adding 4 functions from the functions Tab
![captura de pantalla de 2015-10-10 13-54-59](https://cloud.githubusercontent.com/assets/2364120/10411003/94e89fcc-6f56-11e5-813a-577a1e2e6587.png)

After deleting 3 of the 4 functions.
![captura de pantalla de 2015-10-10 13-55-18](https://cloud.githubusercontent.com/assets/2364120/10411005/a65bb15e-6f56-11e5-9c21-281242e84d62.png)

**Comment by SergioSoto** [comment]
Fixed in commit ccd93b3c71
@acepero13 please corroborate that fixes on FunctionsEditor work properly when you have a chance.

**Comment by acepero13** [comment]
Fixed!
