### ISSUE TITLE
node and edge issue

### ISSUE THREAD

**Issue by TengfeiWang** [SceneMaker/VisualSceneMaker#113]
![nodeandedge](https://cloud.githubusercontent.com/assets/8004177/10417154/c9f76906-7031-11e5-89c9-64dbd8501079.png)

I try to build challenging running environment for scenemaker and have not meet the situation that it freezes. However, when I drag the nodes, I found that the nodes and edges may not close to each other like in the picture.

**Comment by mfallas** [comment]
Fixed 6d00128929915b9ccea3467de1a914134f707412

**Comment by mfallas** [comment]
This issue is still happening under certain circumstances.  When the distance between nodes increases the edges disappear after trying to straighten them.

**Comment by mfallas** [comment]
Fixed e0593318de756fe38fe81dbc5b43fa6448050db4.
