### ISSUE TITLE
Editor Panel should be shown if user drags panel from the minimized state

### ISSUE THREAD

**Issue by SergioSoto** [SceneMaker/VisualSceneMaker#116]
At the moment tha panel remains hidden even though the panel is extended.

<img width="1217" alt="screen shot 2015-10-12 at 11 03 46 am" src="https://cloud.githubusercontent.com/assets/3417219/10424635/f5538a04-70d0-11e5-95ff-cb1896d90265.png">

**Comment by mfallas** [comment]
Fixed 97a2e854114cec377192dfac5a6196809dd676b2
