### ISSUE TITLE
Not matching tags on comments from text copied from web browser

### ISSUE THREAD

**Issue by mfallas** [SceneMaker/VisualSceneMaker#149]
Copying and pasting text from a web page introduces html formatted text that can create errors that crash VSM.

For example:
[Fatal Error] :367:13: The element type "img" must be terminated by the matching end-tag "</img>".

**Comment by mfallas** [comment]
The comment textfield will be changed to accept only text and not html code.

**Comment by acepero13** [comment]
Fixed
