### ISSUE TITLE
VSM lets introduce negative values to time edges

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#156]

**Comment by mfallas** [comment]
Our solution: On TEdge.java modify setTimeout function with and exception ( which is already caught at the view) when the timeout value is invalid.

public void setTimeout(long value) throws Exception {
        if(value >= 0){
            mTimeout = value;
        }else{
            throw new Exception("Invalid Time Out Egde Value");
        }
    }
