### ISSUE TITLE
Integration with YALLAH

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#184]

**Comment by SceneMaker** [comment]
Integration could be done similar to the new charamel character player (`de.dfki.vsm.xtension.charamelWs`, `charamelWsExecutor` resp. `CharacterPlugin`) based on web socket connections.

**Comment by fnunnari** [comment]
Working on the Yallah branch.
The Yallah plugin is there but when I edit the project properties, I can not see Yallah in the list of the devices.

I am starting the editor from the main class, following the instructions at: <https://github.com/SceneMaker/VisualSceneMaker/wiki/Developers-Manual#running-from-within-the-editor>
Should I configure somehow an extension to the class path?

**Comment by algor1th** [comment]
I checked out the current state of the branch and built it using gradle. The yallahExecutor was displayed. Have you removed the import from the VisualScenemaker gradle.build, or the settings.gradle?
![grafik](https://user-images.githubusercontent.com/6415420/92621607-4dbd8800-f2c4-11ea-8ac1-b7a77bf7dd7f.png)

**Comment by fnunnari** [comment]
Can it be because I renamed `yallahExecutor` to `YallahExecutor`?
Where is the code responsible of scanning for existing plugins?

**Comment by algor1th** [comment]
The code for getting the plugins to display in the property manager is located at `java/de/dfki/vsm/xtesting/NewPropertyManager/util/ExtensionsFromJar.java`. Loading plugins on project start is at `RuntimeProject:246`

**Comment by algor1th** [comment]
I found something curious. Scenemaker does not display any plugins when launched via IDEA, but shows all plugins when launched as a jar. Can you reproduce?

**Comment by fnunnari** [comment]
I confirm. I can reproduce. This is quite annoying. I would really prefer to see the plugin when running from the editor, in Debug mode, so that I would be able to do "live coding", i.e., fill in the methods code while the project is running.
This would save tons of development time. The cycle "code->build->run->load->run->observe->repeat" is toooooo slow.

**Comment by fnunnari** [comment]
Closing issue #195 solved this problem. closing.
