### ISSUE TITLE
Instructions on how to create a new Release

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#189]

**Comment by algor1th** [comment]
If you want to create a new release I would recommend to change the version number in the `build.gradle` and in `VisualScenemaker/main/resources/res/version.ini`    
use this as a guideline [semantic versioning](https://semver.org/) and keep the v prefix.
[Creating a github release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

I would also recommend to upload a clean build of vsm along with the release. The versioning plugin may add a `-dirty` to your build if you have untracked changes in the repository. You can make a fresh clone of the release and build it with the gradle wraper (`.\gradlew.bat build` or `./gradlew build`).

**Comment by algor1th** [comment]
However i would like to remark that it may be confusing for users of the application if too many releases are published. I am not sure if it is a good idea to add this to the developer documentation.

**Comment by fnunnari** [comment]
Hi Lenny. Thanks for the updates, but I have some concerns:
- It is a bit impractical that we have to manually edit the version in two different locations. Do you think there is a way to centralize the version number?
- From the instructions, seems that building a release is mandatory in order to run the editor from the IDE (See section `Running from within the editor`). However, I was wondering if there is a way to really run the editor from the code, without building an intermediate `.jar`. This would allow for interactive code editing while the editor is running.
- Having the instructions to build a release doesn't mean that we will create one per week. Just we know where to read when it is needed ;-)   And since it is a seldom process, by the time it is needed, everybody has forgotten it.

**Comment by algor1th** [comment]
I agree that this solution is suboptimal. I have already files an issue, see #175 

For testing, you only need to do the `gradlew build` step and run the jar. If you use intellij, you can go to the main in Scenemaker3 and click the run button, you can save this as a running configuration and use that for testing changes more quickly.
