### ISSUE TITLE
Extension API as package in the extensions folder. Cross-extension reference needed.

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#199]
The top-level API to develop an extension.... is itself an extension!: `de.dfki.vsm.extensionAPI`.
To import the interfaces/classes needed to implement the Plugin parameters, one needs to add a dependency to the `build.gradle`:

```
dependencies {
    compile project(":plugins:extensionAPI")
...
}
```

Personally, I don't really love this solution.

Shouldn't be the extensionAPI just part of the CORE of the system? Together with the `ActivityExecutor` class?

**Comment by algor1th** [comment]
Unfortunately `src/main/java/de/dfki/vsm/extensionAPI/value/ValueRenderable.java` requires a desktop only graphical dempendency. Including it would reduce the portability of the core. For example it would not run on android anymore

**Comment by fnunnari** [comment]
I see. In fact I had another question. When we build a property: why do we have to specify both the property TYPE AND the Rendereable?
Wouldn't be enough to specify just the TYPE and leave the rendering strategy to the GUI builder?

**Comment by algor1th** [comment]
This is definitely worth looking into.

**Comment by fnunnari** [comment]
Closing, sa it is related to the general plugin improvements in. #194
