### ISSUE TITLE
Get string value of runtime string without quotes

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#200]
When executing:
* `Anna: [LookAtObject name=Camera].`, the `ActionFeature.getVal()` returns only `Camera`;
* but when executing `Anna: [LookAtObject name='Camera'].` --> `'Camera'`.

This is rather unexpected. I would expect the parser to remove the single quotes.

This make it difficult to have a SPACES in actions parameter values, as quotes are there mandatory.

* `Anna: [LookAtObject name=Main Camera].` doesn't parse.
* `Anna: [LookAtObject name="Main Camera"].` doesn't parse.
* `Anna: [LookAtObject name='Main Camera'].` is parsing correctly but the parameter value contains ALSO the single quotes
  * `ActionFeature.getVal()` --> 'Main Camera'`.

**Comment by algor1th** [comment]
Changing this would break backward compatibility. Perhaps we could add a new method to get back a string without quotes?
