### ISSUE TITLE
When creating a new plugin, can't import classes needed for properties

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#203]
After branching from `master` (ssi-plugin), I created the directory for a new plugin (ssi).

The following import directories do not work:
```
import de.dfki.vsm.extensionAPI.ExportableProperties;
import de.dfki.vsm.extensionAPI.ProjectProperty;
import de.dfki.vsm.extensionAPI.value.ProjectValueProperty;
```

Actually I can't see package `de.dfki.vsm.extensionAPI`.

That's because the extensionAPI is in the `src` folder, while the plugin can look only in the `core/src`.

In `ssi/build.gradle` this is in and works:

        compile project(":core")

but looking at:

        compile project(":")

gives `Could not resolve project :.`

How can I import the required classes?

**Comment by fnunnari** [comment]
I guess, another solution is that I branch from the YALLAH plugin. Would it work?

**Comment by algor1th** [comment]
Yes, but then you would duplicate all the yallah code into a branch that is  unrelated. You could use git cherry pick to get a single commit from the branch (the one where i moved the plugin interface) and even send a pull request to merge it into master already. Then all branches can profit from that

**Comment by fnunnari** [comment]
Working on that. Can you confirm me that this is the commit to cherry-pick?:

Refactor: Extract extension 
d6d218cb Lenny Händler <lenny@lennyhaendler.com> on 01.04.20 at 16:37

**Comment by algor1th** [comment]
Yes, that should be it
