### ISSUE TITLE
We need a GUI for manually assign variables at run time, outside of the editor

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#210]
For project MindBot, we need a dialog window to enter some data while the project is running.

Ideal behaviour:
* The project starts, and when it reaches a certain state, a dialog window is presented to the user.
  * The dialog can be shown as a web interface, so to have the possibility to control the project also from remote machines.
* The dialog window should be blocking for the project
* The dialog window should be presented as a form, giving the possibility to enter variables.
* (Optional/Advanced) The dialog should allow to load&save "preset" values for the form

**Comment by algor1th** [comment]
#209 can be used for this. It still needs a bit of cleaning up, and the gui has to implement the features we need.
It can:  
- send a "go" signal
- set arbitrary sceneflow variables
- send requests for a variable to be changed (with allowed values)

**Comment by fnunnari** [comment]
The studymaster-web #209 has been indeed enhanced and is no working. Its enhancements are in separate issues.
