### ISSUE TITLE
PlayAction parser doesn't match floats un scientific format

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#230]
When executing a scene like:

    PlayAction("[botty set_tcp_target x=-0.43 y=-0.56 z=0.55 or_w=4.456203E-4]")`

the parser would assign `or_w` to 4.456203. It ignores the "scientific notation"

**Comment by gMehlmann** [comment]
Adapt the flex file's regular expressions for floats and/or cup grammar to
cover such notations.


Fabrizio Nunnari ***@***.***> schrieb am Do., 24. Juni 2021,
17:49:

**Comment by fnunnari** [comment]
> Adapt the flex file's regular expressions for floats and/or cup grammar to cover such notations.

Looks like the parsing was _not_ done by Flex, but rather by a custom regular expression hand-written by Patrik.

**Comment by gMehlmann** [comment]
Right, I remember, whoever it was 😊 Using Antlr would allow to parse such
expressions with the same grammar as used for scenes...

Fabrizio Nunnari ***@***.***> schrieb am So., 27. Juni 2021,
16:11:
