### ISSUE TITLE
StudyMasterWeb Plugin example uses non-existing scene

### ISSUE THREAD

**Issue by SceneMaker** [SceneMaker/VisualSceneMaker#238]
Besides that the explanations how to use the plugin are exceptional good, the scene "SetRequest" does not exist. However, the scene "RequestUserInfo" does exist.

<img width="838" alt="screenshot-substate" src="https://user-images.githubusercontent.com/6949606/125460424-7a9821ac-d885-4a28-9d12-42f5bc9afbc9.png">

**Comment by fnunnari** [comment]
Close by commit 1f366f3a
