### ISSUE TITLE
Work Over Preference Configurations

### ISSUE THREAD

**Issue by gmehlmann** [SceneMaker/VisualSceneMaker#67]
- Are the preferences in the two different preference classes (de.dfki.vsm.editor.util.Preferences and de.dfki.vsm.model.config.ProjectPreferences) really disjunct and are the preferences maintained in the correct configuration file? For example, we have a "node_height" feature in boh configuration files, which makes no sense. Either we use a fix node height for new projects, and then we do not need to configure it, or we save it for each project, which means that it belongs to the project properties.
- Are there preferences that are not really needed any more and if this is the case, could you take them out of the configuration files and the members in the according preferences class?
- Please maintain the preferences in the same format as the other configuration files in scenemaker, in our own xml format, sustained in the classes within the package de.dfki.vsm.model.configs.
- The project preferences may not be in the package de.dfki.vsm.model.configs. This package only defines the configuration classes and format but not the specific configuration, move the project preferences to the model package where the project data is.
- Conclusion: Make the Properties System clean!

**Comment by SergioSoto** [comment]
As suggested by @gmehlmann since commit 85e37f5, de.dfki.vsm.model.project.EditorConfig.java contains only project related configurations which used to be variable static fields in the old preferences file. 

Repeated variables in de.dfki.vsm.editor.util.Preferences.java were removed and now it only contains standard VSM configurations such as colours, folder paths, resources, etc.

Arrangement of both files in their respective package was already made by @gmehlmann in a previous commit

**Comment by SergioSoto** [comment]
As proposed by @gmehlmann, we should merge properties in class *de.dfki.vsm.util.sys.SYSUtilities* with *de.dfki.vsm.model.project.EditorConfig* and *de.dfki.vsm.editor.util.Preferences*, so we have only two configuration classes at the end.

Also, we should move the *de.dfki.vsm.editor.util.Preferences* to a move intuitive package for global variables (de.dfki.vsm was suggested by Gregor as an alternative).

Rename properties file in the user directory  in the user directory from ".scenefloweditor" to ".vsm"

**Comment by SergioSoto** [comment]
commit 409fba8:
Moved properties stored in SYSUtilities to Preferences (as none of the properties in SYSUtilities were project related, there wasn't a reason to put them in EditorConfig) and removed SYSUtilities class.
Also moved Preferences to de.dfki.vsm package and re-added initialization of Preferences removed in previous commit.

commit 16fb5d6:
Renamed file in user directory to *.vsm*
