### ISSUE TITLE
Perference unknown - Crash

### ISSUE THREAD

**Issue by SceneMaker** [SceneMaker/VisualSceneMaker#81]
While opening a new project, the SceneFlowEditor tries to read the showelementproperties property (line 201). On a freshly maschine this is not stored/saved in a file. Result SceneMaker does not create a new project.

**Comment by SceneMaker** [comment]
While opening a new project, the SceneFlowEditor tries to read the showelementproperties property (line 201). On a freshly maschine this is not stored/saved in a file. Result SceneMaker does not create a new project.

**Comment by SergioSoto** [comment]
Fixed
