### ISSUE TITLE
When adding a new variable it does not appear directly in the Variable definition

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#93]
When adding a new variable this one doesn't appear on the variable definition dialog, until the workspace is clicked.

**Comment by SceneMaker** [comment]
This is important, we should have a fix this week

**Comment by SergioSoto** [comment]
Fixed in commit ebc84b4b38 by launching an event that updates VarDefEditor after creating a new variable.

**Comment by SergioSoto** [comment]
@SceneMaker 
SceneMake allows repeated variables with the same name and type. Should this behavior be avoided or handled in a special way?
